CREATE OR REPLACE DATABASE FOOTBALL_DWH;
CREATE OR REPLACE SCHEMA FOOTBALL_DWH.STAGING;
CREATE OR REPLACE SCHEMA FOOTBALL_DWH.DWH;

USE DATABASE FOOTBALL_DWH;
USE SCHEMA STAGING;

CREATE OR REPLACE TABLE STG_EVENT_TYPE AS
SELECT * FROM OPTA_DATA_FOOTBALL__SAMPLE.EPL.EVENT_TYPE;

CREATE OR REPLACE TABLE STG_GAME_STATE AS
SELECT * FROM OPTA_DATA_FOOTBALL__SAMPLE.EPL.GAME_STATE;

CREATE OR REPLACE TABLE STG_PLAYER_POSITION AS
SELECT * FROM OPTA_DATA_FOOTBALL__SAMPLE.EPL.PLAYER_POSITION;

CREATE OR REPLACE TABLE STG_QUALIFIER AS
SELECT * FROM OPTA_DATA_FOOTBALL__SAMPLE.EPL.QUALIFIER;

CREATE OR REPLACE TABLE STG_AFFILIATION AS
SELECT * FROM OPTA_DATA_FOOTBALL__SAMPLE.EPL.AFFILIATION;

CREATE OR REPLACE TABLE STG_COMPETITION AS
SELECT * FROM OPTA_DATA_FOOTBALL__SAMPLE.EPL.COMPETITION;

CREATE OR REPLACE TABLE STG_EVENT AS
SELECT * FROM OPTA_DATA_FOOTBALL__SAMPLE.EPL.EVENT;

CREATE OR REPLACE TABLE STG_EVENT_TYPE_QUALIFIER AS
SELECT * FROM OPTA_DATA_FOOTBALL__SAMPLE.EPL.EVENT_TYPE_QUALIFIER;

CREATE OR REPLACE TABLE STG_GAME AS
SELECT * FROM OPTA_DATA_FOOTBALL__SAMPLE.EPL.GAME;

CREATE OR REPLACE TABLE STG_GAME_OFFICIAL AS
SELECT * FROM OPTA_DATA_FOOTBALL__SAMPLE.EPL.GAME_OFFICIAL;

CREATE OR REPLACE TABLE STG_GAME_PLAYER AS
SELECT * FROM OPTA_DATA_FOOTBALL__SAMPLE.EPL.GAME_PLAYER;

CREATE OR REPLACE TABLE STG_OFFICIAL AS
SELECT * FROM OPTA_DATA_FOOTBALL__SAMPLE.EPL.OFFICIAL;

CREATE OR REPLACE TABLE STG_PLAYER AS
SELECT * FROM OPTA_DATA_FOOTBALL__SAMPLE.EPL.PLAYER;

CREATE OR REPLACE TABLE STG_PLAYER_GAME_STATISTIC AS
SELECT * FROM OPTA_DATA_FOOTBALL__SAMPLE.EPL.PLAYER_GAME_STATISTIC;

CREATE OR REPLACE TABLE STG_TEAM AS
SELECT * FROM OPTA_DATA_FOOTBALL__SAMPLE.EPL.TEAM;

CREATE OR REPLACE TABLE STG_TEAM_GAME_STATISTIC AS
SELECT * FROM OPTA_DATA_FOOTBALL__SAMPLE.EPL.TEAM_GAME_STATISTIC;

CREATE OR REPLACE TABLE STG_VENUE AS
SELECT * FROM OPTA_DATA_FOOTBALL__SAMPLE.EPL.VENUE;

DESC TABLE FOOTBALL_DWH.STAGING.STG_GAME;

USE DATABASE FOOTBALL_DWH;
USE SCHEMA DWH;

CREATE OR REPLACE TABLE DIM_DATE AS
SELECT DISTINCT
  TO_NUMBER(TO_CHAR(TO_DATE(GAME_DATE), 'YYYYMMDD')) AS DATE_KEY,
  TO_DATE(GAME_DATE)                                 AS FULL_DATE,
  YEAR(TO_DATE(GAME_DATE))                           AS YEAR,
  MONTH(TO_DATE(GAME_DATE))                          AS MONTH,
  QUARTER(TO_DATE(GAME_DATE))                        AS QUARTER,
  DAY(TO_DATE(GAME_DATE))                            AS DAY
FROM FOOTBALL_DWH.STAGING.STG_GAME
WHERE GAME_DATE IS NOT NULL;

CREATE OR REPLACE TABLE DIM_GAME AS
SELECT
  ID AS GAME_ID,
  COMPETITION_ID,
  SEASON_ID,
  VENUE_ID,
  HOME_TEAM AS HOME_TEAM_ID,
  AWAY_TEAM AS AWAY_TEAM_ID,
  ATTENDANCE,
  GAME_DATE,
  MATCHDAY,
  GAME_STATE_ID,
  HOME_SCORE,
  HOME_ET_SCORE,
  HOME_FH_SCORE,
  HOME_PEN_SCORE,
  AWAY_SCORE,
  AWAY_ET_SCORE,
  AWAY_FH_SCORE,
  AWAY_PEN_SCORE
FROM FOOTBALL_DWH.STAGING.STG_GAME;

CREATE OR REPLACE TABLE DIM_TEAM AS
SELECT
  ID AS TEAM_ID,
  * EXCLUDE (ID)
FROM FOOTBALL_DWH.STAGING.STG_TEAM;

CREATE OR REPLACE TABLE DIM_PLAYER AS
SELECT
  ID AS PLAYER_ID,
  * EXCLUDE (ID)
FROM FOOTBALL_DWH.STAGING.STG_PLAYER;

CREATE OR REPLACE TABLE DIM_VENUE AS
SELECT
  ID AS VENUE_ID,
  * EXCLUDE (ID)
FROM FOOTBALL_DWH.STAGING.STG_VENUE;

CREATE OR REPLACE TABLE FACT_PLAYER_MATCH AS
WITH base AS (
  SELECT
    pgs.GAME_ID,
    pgs.PLAYER_ID,
    pgs.TEAM_ID,
    TO_DATE(g.GAME_DATE) AS GAME_DAY,
    pgs.GOALS,
    pgs.OWN_GOALS,
    pgs.TOTAL_SCORING_ATT,
    pgs.ONTARGET_SCORING_ATT,
    pgs.BLOCKED_SCORING_ATT,
    pgs.POST_SCORING_ATT,
    pgs.TOTAL_PASS,
    pgs.ACCURATE_PASS,
    pgs.TOTAL_CROSS,
    pgs.ACCURATE_CROSS

  FROM FOOTBALL_DWH.STAGING.STG_PLAYER_GAME_STATISTIC pgs
  JOIN FOOTBALL_DWH.STAGING.STG_GAME g
    ON g.ID = pgs.GAME_ID
)
SELECT
  TO_NUMBER(TO_CHAR(GAME_DAY, 'YYYYMMDD')) AS DATE_KEY,
  GAME_ID,
  PLAYER_ID,
  TEAM_ID,
  GOALS,
  OWN_GOALS,
  TOTAL_SCORING_ATT,
  ONTARGET_SCORING_ATT,
  BLOCKED_SCORING_ATT,
  POST_SCORING_ATT,
  TOTAL_PASS,
  ACCURATE_PASS,
  TOTAL_CROSS,
  ACCURATE_CROSS,

  RANK() OVER (
    PARTITION BY GAME_ID
    ORDER BY GOALS DESC, ONTARGET_SCORING_ATT DESC, TOTAL_SCORING_ATT DESC
  ) AS RANK_IN_GAME,

  SUM(GOALS) OVER (
    PARTITION BY PLAYER_ID
    ORDER BY GAME_DAY
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
  ) AS PLAYER_GOALS_CUMULATIVE

FROM base;
